// <auto-generated />
namespace Data_Access_Layer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TokenTableCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TokenTableCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202409261532592_TokenTableCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
